Remove-ServiceFabricApplication fabric:/CounterActorApplicationCSharp
Unregister-ServiceFabricApplicationType CounterActorApplicationTypeCSharp 1.0.0
 Remove-ServiceFabricApplicationPackage CounterActorApplicationCSharp