Remove-ServiceFabricApplication fabric:/CalculatorActorApplication 
Unregister-ServiceFabricApplicationType CalculatorActorApplicationType 1.0.0
Remove-ServiceFabricApplicationPackage CalculatorActorApplication