Remove-ServiceFabricApplication fabric:/VisualObjectsApplicationCSharp
Unregister-ServiceFabricApplicationType VisualObjectsApplicationTypeCSharp 1.0.0
Remove-ServiceFabricApplicationPackage VisualObjectsApplicationCSharp