Remove-ServiceFabricApplication fabric:/VisualObjectsApplication
Unregister-ServiceFabricApplicationType VisualObjectsApplicationType 1.0.0
Remove-ServiceFabricApplicationPackage VisualObjectsApplication